name: Version JS with Commit Hash

on:
  push:
    branches:
      #- main  # or your default branch
      #- devel
      - feature-gosling-implementation
    paths:
      - 'www/**/*.html'
      - 'www/**/*.js'
      - '.github/workflows/version-js.yml'  # force retrigger if action is modified
      #- 'www/**/*.css'

jobs:
  version-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Add version to JS and CSS references in HTML
        run: |
          find www/ -type f -name "*.html" | while read file; do
            # Clear all existing version tags (in case they are present for files we don't want it on)
            sed -i -E "s/(\.js|\.css)\?v=[^"]*/\1/g" "$file"

            # If path contains "vendor" or "tools" skip
            if [[ "$file" == *"vendor"* || "$file" == *"tools"* ]]; then
              continue
            fi
            #echo $file

            # Add or replace ?v=... for script src and link href (for .js and .css)
            # Only add version to src/href= lines that are local
            sed -i -E "s|(src=\"(js|include)/[^\"]+\.js)(\?v=[^\"]*)?\"|\1?v=${VERSION}\"|g" "$file"
            sed -i -E "s|(href=\"(css|include)/[^\"]+\.css)(\?v=[^\"]*)?\"|\1?v=${VERSION}\"|g" "$file"
          done

      - name: Add version to JS imports in JS files
        run: |
          find www/js www/include -type f -name "*.js" | while read file; do
            # Clear all existing version tags (in case they are present for files we don't want it on)
            sed -i -E 's/(\.js)\?v=[^"\']*/\1/g' "$file"

            # If path contains "vendor" or "tools" skip
            if [[ "$file" == *"vendor"* || "$file" == *"tools"* ]]; then
              continue
            fi
            #echo $file

            # Add or replace ?v=... for import statements (single/double quotes)
            sed -i -E "s|(from ['\"][^'\"]+\.js)(\?v=[^'\"]*)?(['\"])|\1?v=${VERSION}\3|g" "$file"
            sed -i -E "s|(import\(['\"][^'\"]+\.js)(\?v=[^'\"]*)?(['\"])|\1?v=${VERSION}\3|g" "$file"
          done

      # Optional: Commit and push changes back to the repo
      # adding [skip ci] to the commit is important, so that this commit does not trigger the action again.
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add www/*.html www/**/*.html www/js/*.js www/js/**/*.js www/include/**/*.js
          git commit -m "ci: add version hash to JS references (${VERSION}) [skip ci]" || echo "No changes to commit"
          git push